import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';

export const Styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        width: '100%',
        maxWidth: 440,
        maxHeight: '80%',
        flexShrink: 1,
        backgroundColor: Colors.surface,
        borderRadius: 20,
        borderWidth: 1.5,
        borderColor: Colors.primaryAlpha['30'],
        padding: 20,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: Colors.whiteAlpha['08'],
        paddingBottom: 12,
        marginBottom: 16,
    },
    modalTitle: {
        color: Colors.white,
        fontSize: 18,
        fontWeight: '900',
        textTransform: 'uppercase',
    },
    headerBackButton: {
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
        backgroundColor: Colors.whiteAlpha['08'],
    },
    headerBackButtonText: {
        color: Colors.white,
        fontSize: 12,
        fontWeight: 'bold',
    },
    closeModalBtn: {
        padding: 4,
    },
    closeModalBtnText: {
        color: Colors.white,
        fontSize: 18,
    },
    modalSubtitle: {
        color: Colors.whiteAlpha['65'],
        fontSize: 14,
        marginBottom: 16,
    },
    modalScroll: {
        paddingBottom: 16,
    },
    modalGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    modalCard: {
        width: '31%',
        borderRadius: 12,
        borderWidth: 1.5,
        padding: 8,
        alignItems: 'center',
        position: 'relative',
    },
    modalCardShinyStar: {
        position: 'absolute',
        top: 4,
        left: 4,
        fontSize: 10,
    },
    modalCardImage: {
        width: 60,
        height: 60,
        resizeMode: 'contain',
    },
    modalCardName: {
        color: Colors.white,
        fontSize: 11,
        fontWeight: '600',
        textTransform: 'capitalize',
        marginTop: 4,
    },
    modalEmptyState: {
        padding: 24,
        alignItems: 'center',
    },
    modalEmptyText: {
        color: Colors.whiteAlpha['40'],
        fontSize: 14,
        textAlign: 'center',
    },
    modalDetailContainer: {
        alignItems: 'center',
        paddingVertical: 10,
    },
    modalLargeImage: {
        width: 140,
        height: 140,
        resizeMode: 'contain',
        marginBottom: 10,
    },
    shinyLabelBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
        marginBottom: 10,
        shadowColor: '#FFF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 2,
    },
    shinyLabelText: {
        color: Colors.black,
        fontSize: 12,
        fontWeight: 'bold',
    },
    modalPokemonName: {
        color: Colors.white,
        fontSize: 24,
        fontWeight: '900',
        textTransform: 'uppercase',
        marginBottom: 10,
        textAlign: 'center',
    },
    modalTypes: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 20,
    },
    typeBadge: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
        borderWidth: 1.5,
    },
    typeText: {
        fontSize: 12,
        fontWeight: 'bold',
        textTransform: 'capitalize',
    },
    statsSection: {
        width: '100%',
        backgroundColor: Colors.surfaceDeep,
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: Colors.whiteAlpha['06'],
    },
    statsSectionTitle: {
        color: Colors.white,
        fontSize: 16,
        fontWeight: 'bold',
        textTransform: 'uppercase',
        marginBottom: 12,
        letterSpacing: 0.5,
    },
    statBarContainer: {
        marginBottom: 10,
        width: '100%',
    },
    statBarLabelRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    statBarLabel: {
        color: Colors.whiteAlpha['50'],
        fontSize: 12,
        fontWeight: '600',
    },
    statBarValue: {
        color: Colors.white,
        fontSize: 12,
        fontWeight: 'bold',
    },
    statBarBg: {
        height: 6,
        backgroundColor: Colors.whiteAlpha['08'],
        borderRadius: 3,
        overflow: 'hidden',
        width: '100%',
    },
    statBarFill: {
        height: '100%',
        borderRadius: 3,
    },
    actionButton: {
        width: '100%',
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    actionButtonText: {
        color: Colors.white,
        fontSize: 16,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    selectViewContainer: {
        width: '100%',
        flexShrink: 1,
    },
    slotsScroll: {
        gap: 10,
        paddingVertical: 10,
    },
    slotRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 12,
        borderRadius: 16,
        borderWidth: 1.5,
        marginBottom: 8,
    },
    slotRowLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    slotNumber: {
        color: Colors.whiteAlpha['40'],
        fontSize: 12,
        fontWeight: 'bold',
    },
    slotImage: {
        width: 40,
        height: 40,
        resizeMode: 'contain',
    },
    slotName: {
        color: Colors.white,
        fontSize: 14,
        fontWeight: 'bold',
        textTransform: 'capitalize',
    },
    slotShinyStar: {
        fontSize: 12,
    },
    slotSelectAction: {
        fontSize: 12,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
});
